// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRD.Data;

#nullable disable

namespace PRD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251114121435_AddBaseFiscalDoca")]
    partial class AddBaseFiscalDoca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRD.Model.BaseFiscalDoca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Armazem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoriaPlano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjPnExpedidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjTransportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoTransportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companhia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAgenda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataChamada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataChegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEnvioBOSS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRecAgenda")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Devolucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diretoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocaDescarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EanTributario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("HoraAprovacao")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraChamada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraChegada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraEnvioBOSS")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraLancamento")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraRecAgenda")
                        .HasColumnType("time");

                    b.Property<string>("ItemFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemSKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Multicanalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoShow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTransportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProdutoXD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("QtdAgendada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QtdRecebida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecFisico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemessaArmazem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKUOnline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCompra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificadorFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorAgenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorComEstornoBI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorComEstornoLN")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BaseDocaFiscal");
                });

            modelBuilder.Entity("PRD.Model.BaseLNcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Armazem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoriaPlano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjPnExpedidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjTransportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoTransportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companhia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAgenda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataChamada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataChegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEnvioBOSS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRecAgenda")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Devolucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diretoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocaDescarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EanTributario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("HoraAprovacao")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraChamada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraChegada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraEnvioBOSS")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraLancamento")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraRecAgenda")
                        .HasColumnType("time");

                    b.Property<string>("ItemFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemSKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Multicanalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoShow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTransportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProdutoXD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("QtdAgendada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QtdRecebida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecFisico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemessaArmazem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKUOnline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCompra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificadorFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transportadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorAgenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorComEstornoBI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorComEstornoLN")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BaseLN");
                });
#pragma warning restore 612, 618
        }
    }
}
